/* GENERATED by scripts/image-sizes.mjs — do not edit by hand.
   Natural [width, height] of every frame in /public/landing/opt. */

export const IMAGE_SIZES: Record<string, [number, number]> = {
  '/landing/opt/9to5-color.webp': [2500, 1308],
  '/landing/opt/9to5.avif': [2000, 1215],
  '/landing/opt/about.jpeg': [386, 518],
  '/landing/opt/agent3.avif': [1600, 1600],
  '/landing/opt/blank.png': [1200, 800],
  '/landing/opt/bleed-for-the-throne.avif': [1000, 667],
  '/landing/opt/bleed-for-the-throne.webp': [1000, 667],
  '/landing/opt/bleed-for-the-throne1.webp': [1000, 667],
  '/landing/opt/bleed-for-the-throne2.webp': [1000, 667],
  '/landing/opt/coffeefive.avif': [2000, 1597],
  '/landing/opt/cox.png': [704, 540],
  '/landing/opt/ela-rsvp.avif': [2000, 1606],
  '/landing/opt/gestures.webp': [960, 506],
  '/landing/opt/gg.avif': [499, 261],
  '/landing/opt/group-5753.avif': [811, 1600],
  '/landing/opt/hopehydration.avif': [3840, 2565],
  '/landing/opt/img-2808.avif': [1600, 1067],
  '/landing/opt/img-9821.avif': [1600, 1067],
  '/landing/opt/installation-33.avif': [670, 401],
  '/landing/opt/light-around-us.avif': [750, 1333],
  '/landing/opt/light-around-us2.avif': [1000, 1500],
  '/landing/opt/livingwalls.avif': [1400, 1867],
  '/landing/opt/loop.avif': [1600, 1260],
  '/landing/opt/orbitals.avif': [1000, 1397],
  '/landing/opt/pour.avif': [1916, 1536],
  '/landing/opt/render3.avif': [1600, 1075],
  '/landing/opt/sb-pablo.avif': [1500, 1000],
  '/landing/opt/scatter.avif': [1400, 1251],
  '/landing/opt/snow.avif': [1000, 667],
  '/landing/opt/storybooth-1.avif': [1000, 653],
  '/landing/opt/storybooth-2.avif': [1600, 1067],
  '/landing/opt/storybooth-4.avif': [1500, 1000],
  '/landing/opt/suffolk.avif': [1500, 1142],
  '/landing/opt/sugar.avif': [1188, 781],
  '/landing/opt/superbowl.avif': [1034, 766],
}

/** Natural size of a /landing/opt path, falling back to 3:2 when unknown. */
export function imageSize(src: string): { width: number; height: number } {
  const [width, height] = IMAGE_SIZES[src] ?? [1500, 1000]
  return { width, height }
}
