/**
 * Bakes the natural pixel dimensions of every /public/landing/opt image into
 * src/lib/landing-image-sizes.ts.
 *
 * The project index renders photos uncropped at their own aspect ratio, so it
 * needs real dimensions to reserve space (next/image requires width + height,
 * and without them the grid would reflow as each frame decodes).
 *
 * Run after adding or replacing anything in /public/landing/opt:
 *   node scripts/image-sizes.mjs
 */
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const DIR = path.join(process.cwd(), 'public/landing/opt')
const OUT = path.join(process.cwd(), 'src/lib/landing-image-sizes.ts')
const EXT = new Set(['.avif', '.webp', '.jpeg', '.jpg', '.png'])

const files = (await readdir(DIR, { withFileTypes: true }))
  .filter((e) => e.isFile() && EXT.has(path.extname(e.name).toLowerCase()))
  .map((e) => e.name)
  .sort()

const entries = []
for (const name of files) {
  const { width, height } = await sharp(path.join(DIR, name)).metadata()
  if (!width || !height) continue
  entries.push(`  '/landing/opt/${name}': [${width}, ${height}],`)
}

await writeFile(
  OUT,
  `/* GENERATED by scripts/image-sizes.mjs — do not edit by hand.
   Natural [width, height] of every frame in /public/landing/opt. */

export const IMAGE_SIZES: Record<string, [number, number]> = {
${entries.join('\n')}
}

/** Natural size of a /landing/opt path, falling back to 3:2 when unknown. */
export function imageSize(src: string): { width: number; height: number } {
  const [width, height] = IMAGE_SIZES[src] ?? [1500, 1000]
  return { width, height }
}
`,
)

console.log(`wrote ${entries.length} sizes → ${path.relative(process.cwd(), OUT)}`)
